// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class relationInstructorExam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationInstructorExam));
        
        string IMigrationMetadata.Id
        {
            get { return "201912072338123_relation-Instructor-Exam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
