// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class instructorexamrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(instructorexamrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201912091245434_instructor-exam-relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
