// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addingRelationCourseAndQuestion_FK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingRelationCourseAndQuestion_FK));
        
        string IMigrationMetadata.Id
        {
            get { return "201912141803102_addingRelationCourseAndQuestion_FK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
